@startuml idea
actor Operator
actor Client
participant "&#95;_main_&#95;" as main
Client -> FtpServer: STOR big_file.bin
FtpServer -> FtpHandler: STOR big_file.bin
FtpServer <-- FtpHandler: opening data connection
Client <-- FtpServer: opening data connection
Client -> PassiveDTP: (data)
Client <-[#ff0000]-> PassiveDTP: <color:#ff0000>(connection error)</color>
Operator -[#007700]> main: <color:#007700>restart(level)</color>
alt level 0
main -> FtpHandler: restart(0)
FtpHandler -> PassiveDTP: (close)
FtpHandler -> PassiveDTP: (create)
else level 1
main -> FtpHandler: restart(1)
FtpHandler -> PassiveDTP: (close)
FtpHandler -> DTPHandler: (close)
FtpHandler -> DTPHandler: (create)
FtpHandler -> PassiveDTP: (create)
else level 2
main -> FtpHandler: (close)
main -> FtpHandler: (recreate)
else level 3
main -> main: (full restart, likely kill + fork + execv)
end

note over Client
    (continue as normal)
end note
@enduml